package com.miketwo.workouttracker;

import android.app.Activity;
import android.app.AlertDialog;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.os.Bundle;
import android.widget.Button;
import android.widget.LinearLayout;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class ReviewActivity extends Activity {
    @Override public void onCreate(Bundle state){super.onCreate(state);render();}
    private void render(){LinearLayout body=Ui.column(this);Ui.page(this,body);Button back=Ui.smallButton(this,"‹ Home");back.setOnClickListener(v->Ui.openHome(this));body.addView(back);body.addView(Ui.title(this,"History & progress"));SQLiteDatabase db=Db.get(this).getReadableDatabase();renderRecent(body,db);
        int workouts=scalarInt(db,"SELECT COUNT(*) FROM sessions WHERE status<>'active'");int sets=scalarInt(db,"SELECT COUNT(*) FROM set_results WHERE status='complete'");double volume=scalarDouble(db,"SELECT COALESCE(SUM(actual_reps*effective_weight_lb),0) FROM set_results WHERE status='complete'");double cardioMin=scalarDouble(db,"SELECT COALESCE(SUM(duration_min),0) FROM cardio");LinearLayout stats=Ui.card(this);stats.addView(Ui.label(this,"All-time totals"));stats.addView(Ui.heading(this,workouts+" strength workouts  •  "+sets+" sets"));stats.addView(Ui.text(this,WorkoutMath.formatWeight(volume)+" lb total lifting volume",17,Ui.FOREST));stats.addView(Ui.text(this,WorkoutMath.formatWeight(cardioMin)+" cardio minutes",16,Ui.MUTED));body.addView(stats);
        body.addView(Ui.heading(this,"Strength by exercise"));try(Cursor c=db.rawQuery("SELECT exercise_name,COUNT(DISTINCT session_id),MAX(effective_weight_lb),SUM(actual_reps*effective_weight_lb) FROM set_results WHERE status='complete' GROUP BY exercise_name ORDER BY SUM(actual_reps*effective_weight_lb) DESC",null)){while(c.moveToNext()){LinearLayout card=Ui.card(this);card.addView(Ui.exerciseHeader(this,c.getString(0),c.getString(0),21));card.addView(Ui.text(this,c.getInt(1)+" session"+(c.getInt(1)==1?"":"s")+"  •  heaviest "+WorkoutMath.formatWeight(c.getDouble(2))+" lb",15,Ui.MUTED));card.addView(Ui.text(this,WorkoutMath.formatWeight(c.getDouble(3))+" lb total volume",17,Ui.FOREST));body.addView(card);}}
        Button export=Ui.button(this,"Back up or export data",false);export.setOnClickListener(v->startActivity(new android.content.Intent(this,ExportActivity.class)));body.addView(export);}
    private void renderRecent(LinearLayout body,SQLiteDatabase db){LinearLayout recent=Ui.column(this);recent.setPadding(Ui.dp(this,16),Ui.dp(this,10),Ui.dp(this,16),Ui.dp(this,10));recent.setBackground(Ui.bg(Ui.MINT,Ui.dp(this,18)));recent.addView(Ui.heading(this,"Recent activity"));recent.addView(Ui.text(this,"Tap a workout for its summary. Long press to delete.",14,Ui.MUTED));boolean any=false;
        try(Cursor c=db.rawQuery("SELECT kind,id,title,when_at,detail,subdetail FROM (SELECT 'strength' kind,s.id id,s.plan_name title,s.started_at when_at,s.status detail,(SELECT COUNT(*) FROM set_results r WHERE r.session_id=s.id)||' set entries' subdetail FROM sessions s WHERE s.status<>'active' UNION ALL SELECT 'cardio',id,activity,date,printf('%.0f minutes',duration_min),' ' FROM cardio) ORDER BY when_at DESC LIMIT 30",null)){while(c.moveToNext()){any=true;String kind=c.getString(0),title=c.getString(2),detail=c.getString(4);long id=c.getLong(1);LinearLayout card=Ui.card(this);card.addView(Ui.heading(this,kind.equals("strength")?formatDate(c.getString(3)):formatDay(c.getString(3))));card.addView(Ui.text(this,(kind.equals("strength")?"Strength  •  ":"")+title+"  •  "+detail,14,Ui.MUTED));if(kind.equals("strength"))card.addView(Ui.text(this,c.getString(5),16,Ui.INK));card.setOnClickListener(v->startActivity(new android.content.Intent(this,WorkoutSummaryActivity.class).putExtra(kind.equals("strength")?"session_id":"cardio_id",id)));card.setOnLongClickListener(v->{confirmDelete(kind,id,title);return true;});recent.addView(card);}}
        if(!any)recent.addView(Ui.text(this,"Completed workouts will appear here.",17,Ui.MUTED));body.addView(recent);}
    private void confirmDelete(String kind,long id,String name){new AlertDialog.Builder(this).setTitle("Delete workout?").setMessage("Delete "+name+" and its recorded details?").setNegativeButton("Cancel",null).setPositiveButton("Delete workout",(d,w)->{if("strength".equals(kind))Db.get(this).deleteSession(id);else Db.get(this).deleteCardio(id);render();}).show();}
    private int scalarInt(SQLiteDatabase db,String sql){try(Cursor c=db.rawQuery(sql,null)){return c.moveToFirst()?c.getInt(0):0;}}private double scalarDouble(SQLiteDatabase db,String sql){try(Cursor c=db.rawQuery(sql,null)){return c.moveToFirst()?c.getDouble(0):0;}}private String formatDate(String iso){try{return LocalDateTime.parse(iso).format(DateTimeFormatter.ofPattern("MMM d, yyyy"));}catch(Exception e){return iso;}}private String formatDay(String iso){try{return LocalDate.parse(iso).format(DateTimeFormatter.ofPattern("MMM d, yyyy"));}catch(Exception e){return iso;}}
}
