package com.miketwo.workouttracker;

import android.app.Activity;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.os.Bundle;
import android.widget.Button;
import android.widget.LinearLayout;

public class WorkoutSummaryActivity extends Activity {
    @Override public void onCreate(Bundle state){super.onCreate(state);render();}
    private void render(){long session=getIntent().getLongExtra("session_id",0),cardio=getIntent().getLongExtra("cardio_id",0);LinearLayout body=Ui.column(this);Ui.page(this,body);Button back=Ui.smallButton(this,"‹ History");back.setOnClickListener(v->finish());body.addView(back);SQLiteDatabase db=Db.get(this).getReadableDatabase();if(cardio>0){renderCardio(body,db,cardio);return;}renderStrength(body,db,session);}
    private void renderStrength(LinearLayout body,SQLiteDatabase db,long session){String name="Workout";try(Cursor c=db.rawQuery("SELECT plan_name,started_at,notes FROM sessions WHERE id=?",new String[]{String.valueOf(session)})){if(c.moveToFirst()){name=c.getString(0);}}body.addView(Ui.title(this,"Workout summary"));body.addView(Ui.heading(this,name));double volume=scalar(db,"SELECT COALESCE(SUM(actual_reps*effective_weight_lb),0) FROM set_results WHERE session_id=? AND status='complete'",session);body.addView(Ui.text(this,WorkoutMath.formatWeight(volume)+" lb total volume",18,Ui.FOREST));body.addView(Ui.heading(this,"Exercises"));try(Cursor c=db.rawQuery("SELECT exercise_name,COUNT(*),SUM(actual_reps*effective_weight_lb),MAX(effective_weight_lb) FROM set_results WHERE session_id=? AND status='complete' GROUP BY exercise_name,exercise_position ORDER BY MIN(exercise_position)",new String[]{String.valueOf(session)})){while(c.moveToNext()){LinearLayout card=Ui.card(this);card.addView(Ui.exerciseHeader(this,c.getString(0),c.getString(0),21));card.addView(Ui.text(this,c.getInt(1)+" set"+(c.getInt(1)==1?"":"s")+"  •  "+WorkoutMath.formatWeight(c.getDouble(2))+" lb volume",16,Ui.MUTED));card.addView(Ui.text(this,"Top load "+WorkoutMath.formatWeight(c.getDouble(3))+" lb",15,Ui.FOREST));body.addView(card);}}
        int pr=(int)scalar(db,"SELECT COUNT(*) FROM set_results r WHERE r.session_id=? AND r.status='complete' AND r.effective_weight_lb>(SELECT COALESCE(MAX(x.effective_weight_lb),0) FROM set_results x WHERE x.exercise_name=r.exercise_name AND x.status='complete' AND x.session_id<>r.session_id)",session);if(pr>0)body.addView(Ui.heading(this,"Personal best ✦ "+pr+" new top load"+(pr==1?"":"s")));Button edit=Ui.button(this,"Edit workout log",false);edit.setOnClickListener(v->startActivity(new android.content.Intent(this,WorkoutLogEditorActivity.class).putExtra("session_id",session)));body.addView(edit);}
    private void renderCardio(LinearLayout body,SQLiteDatabase db,long id){body.addView(Ui.title(this,"Workout summary"));try(Cursor c=db.rawQuery("SELECT activity,date,duration_min,distance,unit,intervals,notes,laps FROM cardio WHERE id=?",new String[]{String.valueOf(id)})){if(!c.moveToFirst()){finish();return;}body.addView(Ui.heading(this,c.getString(0)));body.addView(Ui.text(this,WorkoutMath.formatWeight(c.getDouble(2))+" minutes  •  "+WorkoutMath.formatWeight(c.getDouble(3))+" "+c.getString(4),18,Ui.FOREST));if(c.getInt(7)>0)body.addView(Ui.text(this,c.getInt(7)+" lengths",16,Ui.MUTED));if(!c.getString(5).isBlank())body.addView(Ui.text(this,c.getString(5),16,Ui.MUTED));if(!c.getString(6).isBlank())body.addView(Ui.text(this,c.getString(6),16,Ui.MUTED));}}
    private double scalar(SQLiteDatabase db,String sql,long id){try(Cursor c=db.rawQuery(sql,new String[]{String.valueOf(id)})){return c.moveToFirst()?c.getDouble(0):0;}}
}
